name: Test
on: [push, pull_request]
jobs:
  test:
    # matrix strategy from: https://github.com/mvdan/github-actions-golang/blob/master/.github/workflows/test.yml
    strategy:
      matrix:
        go-version:
          - 1.18.10
          - 1.19.7
          - 1.20.2
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: go test -race ./...
  sql-test-18:
    strategy:
      matrix:
        containers:
          - 1.18.10-bullseye
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containers }}
    env:
      PGPASSWORD: pgpwd
      PGHOST: postgres
      PGUSER: postgres
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          /go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Run sqlx driver tests
      run: cd db/sql && go test -race ./...
    - name: Run pgx driver tests
      run: cd db/pgx && go test -race ./...
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_PASSWORD: pgpwd
  sql-test-19:
    strategy:
      matrix:
        containers:
          - 1.19.7-bullseye
          - 1.20.2-bullseye
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containers }}
    env:
      PGPASSWORD: pgpwd
      PGHOST: postgres
      PGUSER: postgres
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          /go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Run sqlx driver tests
      run: cd db/sql && go test -race ./...
    - name: Run pgx driver tests
      run: cd db/pgx && go test -race ./...
    - name: Run pgx/v5 driver tests
      run: cd db/pgx/v5 && go test -race ./...
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_PASSWORD: pgpwd
